name: 'Feature Request'
description: 'Use this template if you want to propose new feature'
labels: ["feature"]
assignees:
    - Faboslav
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this feature request!
    - type: textarea
      id: solution-proposal
      attributes:
          label: 'Reproduction Steps'
          description: 'Provide information on how to reproduce this bug. Make sure your instructions are minimal and clear.'
          placeholder: |
              Example:
              1. Spawn mob using spawn egg
              2. Wait for some action
              3. Nothing happens
      validations:
          required: true
    - type: textarea
      id: solution-proposal
      attributes:
          label: 'Solution proposal'
          description: 'Minimal and clear proposal of the solution of what you want to happen.'
      validations:
          required: true
    - type: textarea
      id: solution-alternative
      attributes:
          label: 'Alternative solution'
          description: 'Minimal and clear description of any alternative solution.'
      validations:
          required: false
    - type: textarea
      id: screenshots-and-files
      attributes:
          label: 'Screenshots & files'
          description: 'If appropriate, add screenshots or other files to help explain or showcase your solution.'
          placeholder: 'You can attach your files by dragging & dropping them to this textbox.'
      validations:
          required: false